@isTest
public with sharing class Calculator_Tests {
    // @testSetup
    // static void loadTestData() {}

    // @isTest
    // public static Integer testAddition() {
    //     Test.startTest();
    //     Test.stopTest();
    // }

    // @isTest
    // public static Integer testSubtraction() {
    //     Test.startTest();
    //     Test.stopTest();
    // }

    // @isTest
    // public static Integer testMultiply() {
    //     Test.startTest();
    //     Test.stopTest();
    // }

    // @isTest
    // public static Decimal testDivide() {
    //     Test.startTest();
    //     Test.stopTest();
    // }
}
